### ISSUE TITLE
Handle IP addresses in  get_first_contribution_time()

### ISSUE THREAD

**Issue by roysmith** [roysmith/wp-sock-classifier#3]
```
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-home/roysmith/sock-classifier/env/lib/python3.5/site-packages/mwclient/listing.py", line 55, in __next__
    item = six.next(self._iter)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/utils/get_users_from_archive.py", line 119, in get_suspects
    first_contrib_time = self.get_first_contribution_time(sock)
  File "src/utils/get_users_from_archive.py", line 158, in get_first_contribution_time
    first_edit = contribs.next()
  File "/mnt/nfs/labstore-secondary-tools-home/roysmith/sock-classifier/env/lib/python3.5/site-packages/mwclient/listing.py", line 77, in next
    return self.__next__(*args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-home/roysmith/sock-classifier/env/lib/python3.5/site-packages/mwclient/listing.py", line 61, in __next__
    self.load_chunk()
  File "/mnt/nfs/labstore-secondary-tools-home/roysmith/sock-classifier/env/lib/python3.5/site-packages/mwclient/listing.py", line 97, in load_chunk
    *[(text_type(k), v) for k, v in six.iteritems(self.args)]
  File "/mnt/nfs/labstore-secondary-tools-home/roysmith/sock-classifier/env/lib/python3.5/site-packages/mwclient/client.py", line 235, in get
    return self.api(action, 'GET', *args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-home/roysmith/sock-classifier/env/lib/python3.5/site-packages/mwclient/client.py", line 289, in api
    if self.handle_api_result(info, sleeper=sleeper):
  File "/mnt/nfs/labstore-secondary-tools-home/roysmith/sock-classifier/env/lib/python3.5/site-packages/mwclient/client.py", line 332, in handle_api_result
    info['error']['info'], info['error']['*'])
mwclient.errors.APIError: ('baduser_ucuser', 'Invalid value "174.192.13.32 " for user parameter "ucuser".', 'See https://en.wikipedia.org/w/api.php for API usage. Subscribe to the mediawiki-api-anno
unce mailing list at &lt;https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce&gt; for notice of API deprecations and breaking changes.')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/utils/get_users_from_archive.py", line 223, in <module>
    main()
  File "src/utils/get_users_from_archive.py", line 67, in main
    archive.process()
  File "src/utils/get_users_from_archive.py", line 96, in process
    for suspect in self.get_suspects():
  File "src/utils/get_users_from_archive.py", line 129, in get_suspects
    raise RuntimeError("error in %s" % self.stream.name) from ex
RuntimeError: error in /home/roysmith/sock-classifier/data/temp/AnimeDisneylover95
```

**Comment by roysmith** [comment]
Can't reproduce.  No longer use mwclient.
